void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int mysqrt(int n, int i);
int is_prime_number(int n);
int helper(int i, int n);
int wildcmp(char *s1, char *s2);
int findsrc(char *s, char c, int i, int p);
int _strlen(char *s);
int is_pal(char *s, int start, int end);
int is_palindrome(char *s);
